version: "3.8"

services:
  app:
      build: .
      container_name: crawler_app
      command: bash -c "uvicorn core.main:app --host 0.0.0.0 --port 8000 --reload"
      environment:
        - DATABASE_URL=postgresql://root:root@crawler_db:5432/crawlerdb
        - SECRET_KEY=123abc
        - TOR_PROXY=http://tor-privoxy:8118/
      volumes:
        - .:/core
      ports:
        - 8000:8000
      depends_on:
        - crawler_db
      networks:
        - backend

  crawler_db:
    image: postgres:12.0-alpine
    container_name: crawler_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=crawlerdb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    networks:
      - backend

  tor-privoxy:
    restart: always
    image: dockage/tor-privoxy:latest
    container_name: tor_proxy
    ports:
      - "9050:9050" # Tor proxy
      - "9051:9051" # Tor control port
      - "8118:8118" # Privoxy
    networks:
      - backend
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
  worker:
    build:
      dockerfile: Dockerfile-celery
    container_name: celery_worker
    command: [ 'celery', '-A', 'core.tasks', 'worker', '--loglevel=INFO' ]
    depends_on:
      - redis
    volumes:
      - .:/core
    networks:
      - backend

networks:
  backend:
